spring:
  application:
    name: hello-spring-cloud-admin
server:
  port: 8084


eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
  zipkin:
    base-url: http://localhost:9411
